add_newline = false

[git_status]
conflicted = " 🐗 "
ahead = " 🐇: ${count} "
behind = " 🐢: ${count} "
diverged = " 🔱🐇: ${ahead_count}🔱🐢: ${behind_count} "
untracked = " 🦅: ${count} "
stashed = " 🐫 "
modified = " 🐾: ${count} "
staged = " 🐴: ${count} "
renamed = " 🦋: ${count} "
deleted = " 🐚: ${count} "

[package]
disabled = true
