theme = "gruvbox"

[editor]
mouse = false
rulers = [100]
true-color = true
cursorline = true
auto-completion = true
line-number = "relative"
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true

[keys.insert]
j = { j = "normal_mode", k = "normal_mode" }

[keys.normal]
"S-k" = "hover"
"S-g" = "goto_last_line"
"S-4" = "goto_line_end"
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.select]
"S-g" = "goto_last_line"